apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Um serviço exemplo para o catálogo do Backstage.
  tags:
    - exemplo
    - backend
spec:
  type: service
  lifecycle: production
  owner: squad-transito
