---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: internal-development-platform
spec:
  owner: foundation
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nome-do-meu-servico
  annotations:
    endoflife.date/products: oracle-jdk@8
spec:
  type: service
  lifecycle: production
  owner: foundation
  system: internal-development-platform
  providesApis: [example-grpc-api]
  dependsOn:
    - resource:foundation-db
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: foundation-db
  description: Banco de dados de Foundation
  annotations:
    endoflife.date/products: amazon-rds-postgresql@12
spec:
  type: database
  owner: foundation
  system: internal-development-platform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: devlake-db
  description: Banco de dados de Foundation
  annotations:
    endoflife.date/products: amazon-rds-postgresql@15
spec:
  type: database
  owner: foundation
  system: internal-development-platform